### ISSUE TITLE
Dependency on material_color_utilities for Flutter (master channel)

### ISSUE THREAD

**Issue by algusarov** [rydmike/flex_seed_scheme#6]
It looks like a new version of material_color_utilities was published few days ago at pub_dev (0.5.0) and Flutter SDK now depends on it causing the following issue when using Flutter master and adding flex_color_theme 7.0.5. Possible to update version dependency for this package moving ahead? I know that using Flutter master I should be prepared for such issues, still wanted to give maintainers a heads up on this.

<img width="1378" alt="image" src="https://github.com/rydmike/flex_seed_scheme/assets/46132428/812c853b-5e15-401a-bc87-67e4f681e530">

**Comment by rydmike** [comment]
Thanks I know @algusarov. 

I just made a PR that gets rid of pesky Material Color Utilities (MCU). The fact that Flutter repo depends on it, and MCU is zero-ver, causes constant version conflicts between Flutter stable, beta and master.

Newest version of flex_seed_scheme fixes it by, at least for now, getting rid of the MCU dependency. New releases coming soon of all flex_color_scheme, flex_color_picker and flex_color_scheme that no longer depends on MCU.

You can add a dependency override to your pubspec.yaml like:

```yaml
dependency_overrides:
  material_color_utilities: '>=0.2.0 <0.6.0'
```

This will enable you to use any current Flutter channel.

**Comment by rydmike** [comment]
Version 1.3.0 of package released 

https://pub.dev/packages/flex_seed_scheme

It also solves the issues, but packages `flex_color_scheme` and `flex_color_picker` have not yet been updated to require min 1.3.0 version, but they will update to it if you run pub upgrade, when pub notices there is a newer version.

**Comment by algusarov** [comment]
That's very cool, thanks, @rydmike. I love flex_color_scheme package, thanks a lot for all the hard work on it.
